This module defines a function that multiplies two matrices using numpy method

import method to test
>>> lazy_matrix_mul = __import__('101-lazy_matrix_mul').lazy_matrix_mul

SUCCESSFUL TESTS:
Test with integer and float values:
	>>> m_a = [[1, 2], [3, 4]]
	>>> m_b = [[1, 2], [3, 4]]
	>>> print(lazy_matrix_mul(m_a, m_b))
	[[ 7 10]
 	 [15 22]]

	>>> m_a = [[1, 2]]
	>>> m_b = [[3, 4], [5, 6]]
	>>> print(lazy_matrix_mul(m_a, m_b))
	[[13 16]]

	>>> m_a = [[1.2, 5.5, 6.2], [4.66, 12.3, -9.2]]
	>>> m_b = [[5.0, 3.3], [-2.9, 4.4], [7.2, 4.4]]
	>>> print(lazy_matrix_mul(m_a, m_b))
	[[ 34.69   55.44 ]
	 [-78.61   29.018]]

FAILED TESTS:
Test with an empty matrix
	>>> print(lazy_matrix_mul([], [[2, 0], [1, 2]]))
	Traceback (most recent call last):
	ValueError: shapes (0,) and (2,2) not aligned: 0 (dim 0) != 2 (dim 0)

	>>> print(lazy_matrix_mul([[2, 0], [1, 2]], [[]]))
	Traceback (most recent call last):
	ValueError: shapes (2,2) and (1,0) not aligned: 2 (dim 1) != 1 (dim 0)

Test with different sizes of rows and columns
	>>> m_a = [[1, 2], [3, 4],]
	>>> m_b = [[1, 2], [2, 3], [4, 5]]
	>>> print(lazy_matrix_mul(m_a, m_b))
	Traceback (most recent call last):
	ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

Test with invalid matrices:
	>>> print(lazy_matrix_mul([["5", 3]], [[1, 2]]))
	Traceback (most recent call last):
	ValueError: shapes (1,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)

	>>> m_a = [["6"], ["3"]]
	>>> m_b = [["1"], ["4"]]
	>>> print(lazy_matrix_mul(m_a, m_b))
	Traceback (most recent call last):
	ValueError: shapes (2,1) and (2,1) not aligned: 1 (dim 1) != 2 (dim 0)

	>>> print(lazy_matrix_mul("hello", "world"))
	Traceback (most recent call last):
	ValueError: Scalar operands are not allowed, use '*' instead

Test with None parameters
	>>> print(lazy_matrix_mul(None, None))
	Traceback (most recent call last):
	TypeError: Object arrays are not currently supported

Test with differing row sizes
	>>> m_a = [[1, 2], [3, 4, 5]]
	>>> m_b = [[1, 2], [3, 4]]
	>>> print(lazy_matrix_mul(m_a, m_b))
	Traceback (most recent call last):
	ValueError: setting an array element with a sequence.
